# Generated by Django 5.2.11 on 2026-09-22 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('deleted', 'Deleted'), ('bulk', 'Bulk change')], max_length=16)),
                ('model_label', models.CharField(blank=True, max_length=64)),
                ('object_uuid', models.UUIDField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('actor_level', models.IntegerField(blank=True, null=True)),
                ('actor_kind', models.CharField(blank=True, max_length=16)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('forwarded', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('affected_count', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('successful', models.BooleanField(default=False)),
                ('user_level', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('actor_kind', models.CharField(blank=True, max_length=16)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('forwarded', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
