# Generated by Django 5.2.11 on 2026-09-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0004_commandjob_aborted_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='verify_interval',
            field=models.PositiveIntegerField(default=30, help_text='Seconds between two verification attempts'),
        ),
        migrations.AddField(
            model_name='command',
            name='verify_timeout',
            field=models.PositiveIntegerField(default=300, help_text='Seconds to keep verifying after the payload has run'),
        ),
        migrations.AddField(
            model_name='commandtask',
            name='payload_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commandtask',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandtask',
            name='verification_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandtask',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commandtask',
            name='verify_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commandtask',
            name='verify_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandvariant',
            name='verify_expect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandvariant',
            name='verify_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
