# Generated by Django 5.2.11 on 2026-09-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0007_verify_update_against_router_version'),
        ('router_manager', '0023_routerinformation_available_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandschedule',
            name='exclude_router',
            field=models.ManyToManyField(blank=True, help_text='These devices are left out, also when a selected group brings them in.', related_name='excluded_command_schedules', to='router_manager.router', verbose_name='Excluded routers'),
        ),
        migrations.AddField(
            model_name='commandschedule',
            name='exclude_router_group',
            field=models.ManyToManyField(blank=True, help_text='Every device of these groups is left out, also when another selected group brings it in.', related_name='excluded_command_schedules', to='router_manager.routergroup', verbose_name='Excluded router groups'),
        ),
    ]
