# Generated by Django 5.2.11 on 2026-09-22 20:23

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_commander', '0008_commandschedule_exclude_router_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='schedule_defaults', max_length=16, unique=True)),
                ('start_time', models.TimeField(default=datetime.time(3, 0))),
                ('repeat_interval', models.IntegerField(default=10080)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
