# Generated by Django 5.2.11 on 2026-09-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_manager', '0022_router_password_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerinformation',
            name='available_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routerinformation',
            name='update_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerinformation',
            name='update_requested',
            field=models.BooleanField(default=False),
        ),
    ]
