# Generated by Django 5.2.11 on 2026-09-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_alter_useracl_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracl',
            name='address_link',
            field=models.CharField(choices=[('none', 'No links'), ('ssh', 'Open with SSH'), ('winbox', 'Open with Winbox'), ('both', 'Show a menu (SSH / Winbox)')], default='none', help_text='What a click on the address of a router in the router list does.', max_length=10),
        ),
    ]
